<div id="poncho-header-wrapper">

	<div id="poncho-header">

		<div id="poncho-navigation-wrapper" role="navigation">

			<div id="poncho-navigation-menu" class="poncho-menu">
				<?php echo new OOUI\ButtonWidget( [ 'id' => 'poncho-menu-icon', 'icon' => 'menu', 'framed' => false ] ); ?>
				<ul class="poncho-menu-list">
					<?php foreach ( $this->getNavigationMenu() as $key => $value ) echo $this->makeListItem( $key, $value ); ?>
				</ul>
			</div>

		</div><div id="poncho-logo-wrapper" role="banner">

			<?php $this->logo(); ?>

		</div><div id="poncho-right-menus-wrapper">

			<?php if ( !$this->getSkin()->getConfig()->get( 'HideInterlanguageLinks' ) ): ?>
			<div id="poncho-languages-menu" class="poncho-menu">
				<?php echo new OOUI\ButtonWidget( [ 'id' => 'poncho-notifications-icon', 'icon' => 'textLanguage', 'framed' => false ] ); ?>
				<ul class="poncho-menu-list">
					<?php foreach ( $this->getLanguagesMenu() as $key => $value ) echo $this->makeListItem( $key, $value ); ?>
				</ul>
			</div>
			<?php endif; ?>

			<?php if ( $this->getSkin()->getUser()->isRegistered() ): ?>
			<div id="poncho-notifications-menu" class="poncho-menu">
				<?php echo new OOUI\ButtonWidget( [ 'id' => 'poncho-notifications-icon', 'icon' => 'bell', 'framed' => false ] ); ?>
				<ul class="poncho-menu-list">
					<?php foreach ( $this->getNotifications() as $key => $value ) echo $this->makeListItem( $key, $value ); ?>
				</ul>
			</div>
			<?php endif; ?>

			<div id="poncho-user-menu" class="poncho-menu">
				<?php echo new OOUI\ButtonWidget( [ 'id' => 'poncho-user-icon', 'icon' => 'userAvatar', 'framed' => false ] ); ?>
				<ul class="poncho-menu-list">
					<?php foreach ( $this->getUserMenu() as $key => $value ) echo $this->makeListItem( $key, $value ); ?>
				</ul>
			</div>

		</div><div id="poncho-search-form-wrapper" role="search">

			<form id="poncho-search-form" action="<?php $this->text( 'wgScript' ); ?>">
				<?php echo new OOUI\ButtonWidget( [ 'id' => 'poncho-search-button', 'icon' => 'search', 'framed' => false ] ); ?>
				<?php echo new OOUI\TextInputWidget( [ 'id' => 'poncho-search-input', 'name' => 'search', 'placeholder' => wfMessage( 'search' ) ] ); ?>
				<datalist id="poncho-search-suggestions"></datalist>
			</form>

		</div>

	</div>

</div>

<div id="poncho-content-wrapper">

	<div id="poncho-content">

		<div id="poncho-content-actions">
			<?php foreach ( $this->getMainActions() as $key => $value ) echo $this->makeActionButton( $key, $value ); ?>
			<div id="poncho-more-menu" class="poncho-menu">
				<span class="poncho-menu-item"><?php $this->moreButton(); ?></span>
				<ul class="poncho-menu-list">
					<?php foreach ( $this->getMoreMenu() as $key => $value ) echo $this->makeListItem( $key, $value ); ?>
				</ul>
			</div>
		</div>

		<?php if ( $this->data['indicators'] ): ?>
		<?php echo $this->getIndicators(); ?>
		<?php endif; ?>

		<?php if ( $this->data['sitenotice'] ): ?>
		<div id="siteNotice"><?php $this->html( 'sitenotice' ); ?></div>
		<?php endif; ?>

		<h1 id="firstHeading" class="firstHeading"><?php $this->title(); ?></h1>

		<div id="siteSub"><?php echo $this->msg( 'tagline' ); ?></div>

		<?php if ( $this->data['subtitle'] ): ?>
		<div id="contentSub"><?php $this->html( 'subtitle' ); ?></div>
		<?php endif; ?>

		<?php if ( $this->data['undelete'] ): ?>
		<div id="contentSub2"><?php $this->html( 'undelete' ); ?></div>
		<?php endif; ?>

		<div id="content" class="mw-body" role="main">
			<div id="bodyContent" class="mw-body-content">
				<?php $this->html( 'bodytext' ); ?>
				<?php $this->html( 'catlinks' ); ?>
				<?php $this->html( 'dataAfterContent' ); ?>
			</div>
		</div>

		<?php $this->talkButton(); ?>
		<?php $this->html( 'debughtml' ); ?>

	</div>

</div>

<div id="poncho-footer-wrapper">

	<div id="poncho-footer"><?php $this->footer(); ?></div>

</div>