<?php $this->html( 'headelement' ); ?>

<div id="poncho-header-wrapper">
	<div id="poncho-header">
		<div id="poncho-logo-wrapper">

			<a id="poncho-logo" <?php $this->logoAttributes(); ?>><?php $this->siteName(); ?></a>

		</div><div id="poncho-menu-wrapper">

			<ul id="poncho-menu">
				<?php if ( ExtensionRegistry::getInstance()->isLoaded( 'Echo' ) ): ?>
				<li class="poncho-menu-item">
					<div class="poncho-menu-icon" id="poncho-bell-icon"></div>
					<ul class="poncho-menu-list">
						<?php foreach ( $this->getNotifications() as $key => $value ) echo $this->makeListItem( $key, $value ); ?>
					</ul>
				</li>
				<?php endif; ?>
				<li class="poncho-menu-item">
					<div class="poncho-menu-icon" id="poncho-user-icon"></div>
					<ul class="poncho-menu-list">
						<?php foreach ( $this->getUserMenu() as $key => $value ) echo $this->makeListItem( $key, $value ); ?>
					</ul>
				</li>
				<li class="poncho-menu-item">
					<div class="poncho-menu-icon" id="poncho-menu-icon"></div>
					<ul class="poncho-menu-list">
						<?php foreach ( $this->getMainMenu() as $key => $value ): ?>
							<?php if ( $key === 'navigation' ): ?>
								<?php foreach ( $value as $k => $v ) echo $this->makeListItem( $k, $v ); ?>
							<?php else: ?>
								<li class="poncho-submenu-item">
									<span class="poncho-submenu-span"><?php echo $key; ?></span>
									<ul class="poncho-submenu">
										<?php foreach ( $value as $k => $v ) echo $this->makeListItem( $k, $v ); ?>
									</ul>
								</li>
							<?php endif; ?>
						<?php endforeach; ?>
					</ul>
				</li>
			</ul>

		</div><div id="poncho-search-form-wrapper">

			<form id="poncho-search-form" action="<?php $this->text( 'wgScript' ); ?>"><?php $this->searchInput(); ?></form>

		</div>
	</div>
</div>

<div id="poncho-content-wrapper">

	<?php if ( $this->data['indicators'] ): ?>
	<?php echo $this->getIndicators(); ?>
	<?php endif; ?>

	<?php if ( $this->getNamespaces() ): ?>
	<ul id="poncho-namespaces">
		<?php foreach ( $this->getNamespaces() as $key => $value ) echo $this->makeListItem( $key, $value ); ?>
	</ul>
	<?php endif; ?>

	<?php if ( $this->getActions() ): ?>
	<ul id="poncho-actions">
		<?php foreach ( $this->getActions() as $key => $value ) echo $this->makeListItem( $key, $value ); ?>
	</ul>
	<?php endif; ?>

	<?php if ( $this->data['sitenotice'] ): ?>
	<div id="siteNotice"><?php $this->html( 'sitenotice' ); ?></div>
	<?php endif; ?>

	<h1 id="firstHeading" class="firstHeading"><?php $this->html( 'title' ); ?></h1>

	<div id="siteSub"><?php $this->msg( 'tagline' ); ?></div>

	<?php if ( $this->data['subtitle'] ): ?>
	<div id="contentSub"><?php $this->html( 'subtitle' ); ?></div>
	<?php endif; ?>

	<?php if ( $this->data['undelete'] ): ?>
	<div id="contentSub2"><?php $this->html( 'undelete' ); ?></div>
	<?php endif; ?>

	<?php if ( $this->data['newtalk'] ): ?>
	<div class="usermessage"><?php $this->html( 'newtalk' ); ?></div>
	<?php endif; ?>

	<div id="content" class="mw-body">
		<div id="bodyContent" class="mw-body-content">

			<?php $this->html( 'bodytext' ); ?>

			<?php $this->html( 'dataAfterContent' ); ?>

			<?php $this->html( 'catlinks' ); ?>

		</div>
	</div>

	<?php $this->html( 'debughtml' ); ?>

</div>

<div id="poncho-footer-wrapper">
	<div id="poncho-footer">
		<ul id="poncho-footer-tools">
			<?php foreach ( $this->getTools() as $key => $value ) echo $this->makeListItem( $key, $value ); ?>
		</ul>
		<?php echo $this->getFooter(); ?>
	</div>
</div>

<?php $this->printTrail(); ?>

</body>
</html>